import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TelegramProvider from "@/components/TelegramProvider";
import ReduxProvider from "@/store/ReduxProvider";
import { useAppSelector } from "@/store/hooks";
import RootHeader from "@/components/RootHeader";
import { AnimatePresence } from "framer-motion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = useAppSelector((state)=>state.user.isAuthenticated)
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReduxProvider>
          <TelegramProvider>
            <AnimatePresence>
              {isAuthenticated && <RootHeader/>}
              {children}
            </AnimatePresence>
          </TelegramProvider>
        </ReduxProvider>
        </body>
    </html>
  );
}
